{
 "title": "System Monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Node Free Storage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/sda1\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Node Free Memory (RAM + Swap) %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemFree_bytes + node_memory_SwapFree_bytes)/(node_memory_MemTotal_bytes + node_memory_SwapTotal_bytes)*100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Node Free RAM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Node Process Virtual Mem Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Node CPU Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "sort term" },
    { "expr": "node_load5", "legendFormat": "mid term" },
    { "expr": "node_load15", "legendFormat": "long term" }
   ]
  },
  {
   "title": "High Load Alert",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ALERTS{alertname=\"HighLoad\", alertstate=\"firing\"}",
     "legendFormat": "{{alertname}}"
    }
   ]
  },
  {
   "title": "Load Status",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ALERTS{alertname=\"HighLoad\",alertstate=\"firing\"}"
    }
   ]
  }
 ]
}